/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#include "ns3/applications-module.h"
#include "ns3/core-module.h"
#include "ns3/csma-module.h"
#include "ns3/internet-module.h"
#include "ns3/network-module.h"
#include "ns3/p4-switch-module.h"

#include <fstream>
#include <iostream>

using namespace ns3;

NS_LOG_COMPONENT_DEFINE("P4SwitchExample");

int
main(int argc, char* argv[])
{
    LogComponentEnable("P4SwitchExample", LOG_LEVEL_INFO);
    LogComponentEnable("P4SwitchNetDevice", LOG_LEVEL_DEBUG);

    CommandLine cmd;
    cmd.Parse(argc, argv);

    NS_LOG_INFO("Create nodes.");
    NodeContainer terminals;
    terminals.Create(4);

    NodeContainer csmaSwitch;
    csmaSwitch.Create(1);

    NS_LOG_INFO("Build Topology");
    CsmaHelper csma;
    csma.SetChannelAttribute("DataRate", DataRateValue(5000000));
    csma.SetChannelAttribute("Delay", TimeValue(MilliSeconds(2)));

    NetDeviceContainer terminalDevices;
    NetDeviceContainer switchDevices;
    for (int i = 0; i < 4; i++)
    {
        NetDeviceContainer link = csma.Install(NodeContainer(terminals.Get(i), csmaSwitch));
        terminalDevices.Add(link.Get(0));
        switchDevices.Add(link.Get(1));
    }

    Ptr<Node> switchNode = csmaSwitch.Get(0);
    P4SwitchHelper p4switch;
    p4switch.SetDeviceAttribute(
        "PipelineJson",
        StringValue("/ns3/ns-3.40/src/p4-switch/examples/livelive_build/srv6_livelive.json"));
    p4switch.SetDeviceAttribute(
        "PipelineCommands",
        StringValue(
            "mc_mgrp_create 1\nmc_node_create 1 2 3\nmc_node_associate 1 0\ntable_add "
            "check_live_live_enabled live_live_mcast 2001::/64 => 1 e1::2\ntable_set_default "
            "check_live_live_enabled ipv6_encap_forward e1::2 2\ntable_add srv6_forward "
            "add_srv6_dest_segment 2 => c3::e2\ntable_add srv6_forward add_srv6_dest_segment 3 => "
            "c4::e2\ntable_add srv6_live_live_forward add_srv6_ll_segment 1 => e2::55\ntable_add "
            "srv6_function srv6_ll_deduplicate 85 => \ntable_add ipv6_forward forward 2001::/64 => "
            "1 0x0000000ae100"));
    p4switch.Install(switchNode, switchDevices);

    InternetStackHelper internetV6only;
    internetV6only.SetIpv4StackInstall(false);
    internetV6only.Install(terminals);

    NS_LOG_INFO("Assign IP Addresses.");
    Ipv6AddressHelper ipv6;
    ipv6.SetBase(Ipv6Address("2001::"), Ipv6Prefix(64));
    ipv6.Assign(terminalDevices);

    Ptr<NetDevice> netDevice0 = terminalDevices.Get(0);
    Ptr<Node> node0 = netDevice0->GetNode();
    int32_t ipv6InterfaceIndex0 = node0->GetObject<Ipv6>()->GetInterfaceForDevice(netDevice0);
    Ptr<Ipv6Interface> ipv6Interface0 =
        node0->GetObject<Ipv6L3Protocol>()->GetInterface(ipv6InterfaceIndex0);
    std::cout << ipv6Interface0 << std::endl;

    Ptr<NetDevice> netDevice1 = terminalDevices.Get(1);
    Ptr<Node> node1 = netDevice1->GetNode();
    int32_t ipv6InterfaceIndex1 = node1->GetObject<Ipv6>()->GetInterfaceForDevice(netDevice1);
    Ptr<Ipv6Interface> ipv6Interface1 =
        node1->GetObject<Ipv6L3Protocol>()->GetInterface(ipv6InterfaceIndex1);
    std::cout << ipv6Interface1 << std::endl;

    Ptr<NdiscCache> ndiscCache = ipv6Interface0->GetNdiscCache();
    NdiscCache::Entry* entry = ndiscCache->Lookup(Ipv6Address("2001::2"));
    if (!entry)
    {
        NS_LOG_INFO("ADD an ARP entry");
        entry = ndiscCache->Add(Ipv6Address("2001::2"));
    }
    entry->SetMacAddress(netDevice1->GetAddress());
    entry->MarkAutoGenerated();

    NS_LOG_INFO("Create Applications.");
    uint16_t port = 9;
    OnOffHelper onoff("ns3::UdpSocketFactory",
                      Address(Inet6SocketAddress(Ipv6Address("2001::2"), port)));
    onoff.SetConstantRate(DataRate("500kb/s"));

    ApplicationContainer app = onoff.Install(terminals.Get(0));
    app.Start(Seconds(1.0));
    app.Stop(Seconds(10.0));

    PacketSinkHelper sink("ns3::UdpSocketFactory",
                          Address(Inet6SocketAddress(Ipv6Address::GetAny(), port)));
    app = sink.Install(terminals.Get(1));
    app.Start(Seconds(0.0));

    NS_LOG_INFO("Configure Tracing.");
    AsciiTraceHelper ascii;
    csma.EnableAsciiAll(ascii.CreateFileStream("p4-switch.tr"));
    csma.EnablePcapAll("p4-switch", true);

    NS_LOG_INFO("Run Simulation.");
    Simulator::Run();
    Simulator::Destroy();
    NS_LOG_INFO("Done.");
}
